use std::process::Command;

static TARGET_PATH: &str = "../user/target/riscv64gc-unknown-none-elf/release/";

fn main() {
    println!("cargo:rerun-if-changed=../user/src/");
    println!("cargo:rerun-if-changed={}", TARGET_PATH);

    let elf = kernel_elf_path();
    println!("cargo:rerun-if-changed={}", elf);

    generate_symbol_table(&elf);
    generate_line_table(&elf);
}

/// Path to the built kernel ELF, derived from the cargo build environment.
fn kernel_elf_path() -> String {
    let target_dir =
        std::env::var("CARGO_TARGET_DIR").unwrap_or_else(|_| "target".to_string());
    let target = std::env::var("TARGET")
        .unwrap_or_else(|_| "riscv64gc-unknown-none-elf".to_string());
    let profile = std::env::var("PROFILE").unwrap_or_else(|_| "release".to_string());
    format!("{}/{}/{}/os", target_dir, target, profile)
}

/// Generate a kernel symbol table (from `nm` on the kernel ELF) so that the
/// panic backtrace in `src/unwind.rs` can translate a `ra` address into
/// `symbol+offset` instead of a bare hex number.
///
/// The table is written to `OUT_DIR/symbols.rs` and `include!`d by `unwind.rs`.
///
/// Inherent one-build lag: `build.rs` runs *before* the linker produces the ELF,
/// so this table reflects the *previous* build's ELF. On the next build the ELF
/// has changed, `build.rs` reruns (via `cargo:rerun-if-changed`), and the table
/// catches up. Function names are stable across small edits, so this is close
/// enough for backtrace debugging; run `make kernel` twice for an exact match.
fn generate_symbol_table(elf: &str) {
    let out_dir = std::env::var("OUT_DIR").unwrap();
    let dest = std::path::Path::new(&out_dir).join("symbols.rs");

    let content = match collect_symbols(elf) {
        Some(rows) => format_symbol_table(&rows),
        None => {
            // ELF not built yet (cold build) or nm unavailable: emit an empty
            // table so the kernel still compiles and prints bare addresses.
            "// symbol table unavailable (kernel ELF not built yet or nm missing)\n\
             pub static SYMBOLS: &[(usize, &str)] = &[];\n"
                .to_string()
        }
    };
    std::fs::write(&dest, content).unwrap();
}

/// Run `nm` on the kernel ELF and collect (addr, demangled-name) for code symbols.
fn collect_symbols(elf: &str) -> Option<Vec<(usize, String)>> {
    let output = ["rust-nm", "llvm-nm", "nm"]
        .iter()
        .find_map(|tool| {
            Command::new(tool)
                .arg(elf)
                .output()
                .ok()
                .filter(|o| o.status.success())
        })?;
    let text = String::from_utf8_lossy(&output.stdout);
    let mut rows = Vec::new();
    for line in text.lines() {
        // nm line format: "<addr> <type> <name>"  e.g. "0000000080200000 T rust_main"
        let parts: Vec<&str> = line.split_whitespace().collect();
        if parts.len() < 3 {
            continue;
        }
        let typ = parts[1];
        // Only symbols in the text (code) section. 'T' = global, 't' = local.
        if typ != "T" && typ != "t" {
            continue;
        }
        let Ok(addr) = usize::from_str_radix(parts[0], 16) else {
            continue;
        };
        let name = parts[2..].join(" ");
        // Skip assembler/compiler local labels (e.g. ".Lpcrel_hi0", ".L0") —
        // they are not real functions and only clutter the backtrace.
        if name.starts_with('.') || name.starts_with("LBB") || name.starts_with("Ltmp") {
            continue;
        }
        let mut demangled = rustc_demangle::demangle(name.as_str()).to_string();
        demangled = strip_instance_hash(&demangled);
        rows.push((addr, demangled));
    }
    rows.sort_by_key(|(a, _)| *a);
    rows.dedup_by_key(|(a, _)| *a);
    Some(rows)
}

/// Strip a trailing Rust instance-disambiguator hash like `::h1fa33bcd2793d9ee`
/// (16 hex chars) so backtrace names read as the human function path.
fn strip_instance_hash(name: &str) -> String {
    let Some(tail) = name.rsplit("::").next() else {
        return name.to_string();
    };
    let is_hash = tail.len() == 17
        && tail.starts_with('h')
        && tail[1..].chars().all(|c| c.is_ascii_hexdigit());
    if is_hash {
        name[..name.len() - tail.len() - 2].to_string()
    } else {
        name.to_string()
    }
}

fn format_symbol_table(rows: &[(usize, String)]) -> String {
    let mut s = String::from(
        "// auto-generated by build.rs from `nm <kernel-elf>`. DO NOT EDIT.\n\
         pub static SYMBOLS: &[(usize, &str)] = &[\n",
    );
    for (addr, name) in rows {
        // Escape any backslashes/quotes in (demangled) names defensively.
        let esc = name.replace('\\', "\\\\").replace('"', "\\\"");
        s.push_str(&format!("    ({:#x}, \"{}\"),\n", addr, esc));
    }
    s.push_str("];\n");
    s
}

// ---------------------------------------------------------------------------
// Source-line table (for `符号+偏移 文件名:行号` backtraces)
//
// Generated from DWARF debug info via `llvm-dwarfdump` (to enumerate line-table
// boundary addresses) + `addr2line` (to resolve each to `file:line`). The table
// is sorted by address and looked up at panic time with a binary search, so any
// `ra` resolves to the source line of the instruction it lands in.
//
// Robustness: if debug info is absent (e.g. built without `debug = true`), or the
// ELF/tools are unavailable, an EMPTY table is emitted. The kernel then keeps
// printing `符号+偏移 at ?` instead of a file:line — it never crashes.
// ---------------------------------------------------------------------------

fn generate_line_table(elf: &str) {
    let out_dir = std::env::var("OUT_DIR").unwrap();
    let dest = std::path::Path::new(&out_dir).join("lines.rs");

    let content = match collect_line_table(elf) {
        Some(t) => format_line_table(&t),
        None => empty_lines_file(),
    };
    std::fs::write(&dest, content).unwrap();
}

struct LineTable {
    addrs: Vec<u32>,   // sorted ascending
    files: Vec<u16>,   // index into `file_table`; 0 == unknown
    lines: Vec<u16>,   // 0 == unknown
    file_table: Vec<String>, // file_table[0] == "<unknown>"
}

fn collect_line_table(elf: &str) -> Option<LineTable> {
    // 1. Enumerate line-table boundary addresses from DWARF (`--debug-line`).
    //    Each printed row starting with `0x` is `addr line col file isa flags`;
    //    skip `end_sequence` rows (their (file,line) is meaningless).
    let dump = Command::new("llvm-dwarfdump")
        .arg("--debug-line")
        .arg(elf)
        .output()
        .ok()
        .filter(|o| o.status.success())?;
    let dump_text = String::from_utf8_lossy(&dump.stdout);
    let mut addrs: Vec<u32> = Vec::new();
    for line in dump_text.lines() {
        if !line.starts_with("0x") {
            continue;
        }
        if line.contains("end_sequence") {
            continue;
        }
        let mut it = line.split_whitespace();
        let Some(addr_s) = it.next() else { continue };
        let a = u64::from_str_radix(addr_s.trim_start_matches("0x"), 16).ok()?;
        if a > 0xFFFF_FFFF {
            continue;
        }
        addrs.push(a as u32);
    }
    addrs.sort_unstable();
    addrs.dedup();
    // No rows ⇒ no debug info: fall back to the empty table (all `?`).
    if addrs.is_empty() {
        return None;
    }

    // 2. Resolve every boundary address to `file:line` in one `addr2line` batch.
    //    It prints two lines per address (function, then location) in input
    //    order; we only consume the location line (the function name comes from
    //    the nm-based symbol table).
    let mut cmd = Command::new("addr2line");
    cmd.arg("-e").arg(elf).arg("-f").arg("-C");
    for a in &addrs {
        cmd.arg(format!("0x{:x}", a));
    }
    let out = cmd.output().ok()?;
    // Don't hard-fail on nonzero status (some addr2line builds warn on stderr);
    // rely on stdout presence instead. But require non-empty stdout.
    let txt = String::from_utf8_lossy(&out.stdout);
    if txt.is_empty() {
        return None;
    }

    let mut file_table: Vec<String> = vec!["<unknown>".to_string()];
    let mut file_map: std::collections::HashMap<String, u16> = std::collections::HashMap::new();
    file_map.insert("<unknown>".to_string(), 0u16);

    let mut rows_addrs: Vec<u32> = Vec::new();
    let mut rows_files: Vec<u16> = Vec::new();
    let mut rows_lines: Vec<u16> = Vec::new();

    let mut loc_lines = txt.lines();
    for a in &addrs {
        // Skip the function-name line.
        let _ = loc_lines.next();
        let Some(loc) = loc_lines.next().map(str::trim) else { break };
        let (file, line) = match parse_addr2line_loc(loc) {
            Some(fl) => fl,
            None => ("<unknown>".to_string(), 0u16),
        };
        let fid = match file_map.get(&file) {
            Some(&i) => i,
            None => {
                let i = file_table.len() as u16;
                file_table.push(file.clone());
                file_map.insert(file.clone(), i);
                i
            }
        };
        // Collapse consecutive identical (file,line): keeping only the first
        // address of a run is correct for "nearest-lower" lookup and shrinks
        // the table without losing any source-line resolution.
        let same_as_last = !rows_files.is_empty()
            && *rows_files.last().unwrap() == fid
            && *rows_lines.last().unwrap() == line;
        if !same_as_last {
            rows_addrs.push(*a);
            rows_files.push(fid);
            rows_lines.push(line);
        }
    }

    if rows_addrs.is_empty() {
        return None;
    }
    Some(LineTable {
        addrs: rows_addrs,
        files: rows_files,
        lines: rows_lines,
        file_table,
    })
}

/// Parse an `addr2line` location string like `src/x.rs:117` /
/// `/abs/path.rs:6` / `??:0` / `file:?` into `(file, line)`. Returns `None` for
/// anything that cannot be turned into a real (file, line).
fn parse_addr2line_loc(loc: &str) -> Option<(String, u16)> {
    // Strip trailing " (discriminator N)" if present.
    let loc = loc.split(" (").next().unwrap_or(loc);
    if loc.is_empty() || loc == "??" || loc == "??:0" || loc == "??:0:0" {
        return None;
    }
    let i = loc.rfind(':')?;
    let file = &loc[..i];
    if file == "??" || file.is_empty() {
        return None;
    }
    let rest = &loc[i + 1..];
    // `rest` is `line` or `line:column`; take just the line part.
    let line_s = rest.split(':').next().unwrap_or(rest);
    let line: u32 = line_s.parse().ok()?;
    if line == 0 || line > 65535 {
        return None;
    }
    Some((file.to_string(), line as u16))
}

fn format_line_table(t: &LineTable) -> String {
    let mut s = String::from(
        "// auto-generated by build.rs from DWARF debug info. DO NOT EDIT.\n",
    );
    // File name table. Index 0 is the "<unknown>" sentinel.
    s.push_str("pub static LINE_FILE_TABLE: &[&str] = &[\n");
    for f in &t.file_table {
        let esc = f.replace('\\', "\\\\").replace('"', "\\\"");
        s.push_str(&format!("    \"{}\",\n", esc));
    }
    s.push_str("];\n");

    // Three parallel, address-sorted arrays. Looked up by binary search at
    // panic time (nearest-lower address ⇒ source line of the instruction).
    write_u32_array(&mut s, "LINE_ADDRS", &t.addrs, true);
    write_u16_array(&mut s, "LINE_FILES", &t.files, false);
    write_u16_array(&mut s, "LINE_LINES", &t.lines, false);
    s
}

fn write_u32_array(s: &mut String, name: &str, vals: &[u32], hex: bool) {
    s.push_str(&format!("pub static {}: &[u32] = &[", name));
    for (i, v) in vals.iter().enumerate() {
        if i % 12 == 0 {
            s.push_str("\n    ");
        }
        if hex {
            s.push_str(&format!("0x{:08x}, ", v));
        } else {
            s.push_str(&format!("{}, ", v));
        }
    }
    if !vals.is_empty() {
        s.push('\n');
    }
    s.push_str("];\n");
}

fn write_u16_array(s: &mut String, name: &str, vals: &[u16], _hex: bool) {
    s.push_str(&format!("pub static {}: &[u16] = &[", name));
    for (i, v) in vals.iter().enumerate() {
        if i % 16 == 0 {
            s.push_str("\n    ");
        }
        s.push_str(&format!("{}, ", v));
    }
    if !vals.is_empty() {
        s.push('\n');
    }
    s.push_str("];\n");
}

fn empty_lines_file() -> String {
    "// line table unavailable (no DWARF debug info, or ELF/tools not built yet).\n\
     // The kernel prints `符号+偏移 at ?` instead of a file:line; it never crashes.\n\
     pub static LINE_FILE_TABLE: &[&str] = &[\"<unknown>\"];\n\
     pub static LINE_ADDRS: &[u32] = &[];\n\
     pub static LINE_FILES: &[u16] = &[];\n\
     pub static LINE_LINES: &[u16] = &[];\n"
        .to_string()
}
